# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  api:
    url:
      category: http://category.svc:8080
      location: http://location:8080
  from:
    cluster: test-cluster-01
    
logging:
  level:
    com:
      vmware: DEBUG

server:
  port: 8080

